### ISSUE TITLE
不知道如何升级deepin-wine-helper (>= 1.1deepin3)？

### ISSUE THREAD

**Issue by isaac574** [lturing/ubuntu18-deepwine-wechat#1]
你好，按博主的安装方法，虽然报错，昨天WECHAT依然可以启动（在pop os 20.10平台下）。但今天发现WECHAT LOGO消失，不知道哪里去找程序，一头雾水。呈上报错信息如下：
isaacsheng@pop-os:~/ubuntu18-deepwine-wechat$ sudo dpkg -i --force-overwrite deepin.com.wechat_2.6.2.31deepin0_i386.deb
正在选中未选择的软件包 deepin.com.wechat:i386。
(正在读取数据库 ... 系统当前共安装有 232910 个文件和目录。)
准备解压 deepin.com.wechat_2.6.2.31deepin0_i386.deb  ...
正在解压 deepin.com.wechat:i386 (2.6.2.31deepin0) ...
dpkg: 依赖关系问题使得 deepin.com.wechat:i386 的配置工作不能继续：
 deepin.com.wechat:i386 依赖于 deepin-wine-helper (>= 1.1deepin3).

dpkg: 处理软件包 deepin.com.wechat:i386 (--install)时出错：
 依赖关系问题 - 仍未被配置
正在处理用于 gnome-menus (3.36.0-1ubuntu1) 的触发器 ...
正在处理用于 desktop-file-utils (0.24-1ubuntu4) 的触发器 ...
正在处理用于 mime-support (3.64ubuntu1) 的触发器 ...
正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...
在处理时有错误发生：
 deepin.com.wechat:i386

不知道如何升级deepin-wine-helper (>= 1.1deepin3)？
盼指教！

**Comment by lturing** [comment]
抱歉，你这个估计是版本不兼容。我提供的是在ubuntu18上安装微信。
可以试试国产的linux系统 https://www.deepin.org/zh/，支持安装微信，qq等
